QDRANT_HOST = "localhost"
QDRANT_PORT = 6333
COLLECTION_NAME = "monit_rag_collection"

EMBED_MODEL = "nomic-embed-text"
LLM_MODEL = "gemma2:2b"

VECTOR_SIZE = 768
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 150

RETRIEVAL_LIMIT = 5
SCORE_THRESHOLD = 0.35
LEXICAL_BONUS = 0.15